### ISSUE TITLE
Замінити API лінк на сервіс тривог

### ISSUE THREAD

**Issue by Vadimkin** [and3rson/raid#3]
Привіт!

Якщо все ще використовуєте API повітряних тривог, то замініть, будь ласка, `https://emapa.fra1.cdn.digitaloceanspaces.com/statuses.json` → `https://vadimklimenko.com/map/statuses.json`, там повністю відповідь 1-в-1. Приблизно через тиждень я перестану оновлювати файл на DO Spaces (перший лінк).

Дякую!

https://github.com/and3rson/raid/blob/aa5c30ffb95cf10228f0e04f90abeceefbaf65c2/better_days/fetch_states.py#L6-L11

**Comment by curiousartem** [comment]
Створив Pull Request
#4
